apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: green-datacenter-selector
  labels:
    app: green-datacenter-selector
    app.kubernetes.io/name: green-datacenter-selector
    app.kubernetes.io/component: frontend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/andrewlaidlaw/green-datacenter-selector.git
      ref: OpenShift
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:22-ubi9
        namespace: openshift
      env:
      - name: NODE_ENV
        value: production
  output:
    to:
      kind: ImageStreamTag
      name: green-datacenter-selector:latest
  triggers:
  - type: ConfigChange
  - type: ImageChange
  runPolicy: Serial

# Made with Bob
