apiVersion: v1
kind: Service
metadata:
  name: green-datacenter-selector
  labels:
    app: green-datacenter-selector
    app.kubernetes.io/name: green-datacenter-selector
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: green-datacenter-selector
  sessionAffinity: None

# Made with Bob
